### PR TITLE
[tests] enable testing for xpu 

### PR DESCRIPTION
**Pull request by faaany**
## What does this PR do?
below is an example: 
```
======================================================== short test summary info =========================================================
PASSED test/tensor/activations/test_activations_compile.py::test_compile_qtensor_to[cpu]
PASSED test/tensor/activations/test_activations_compile.py::test_compile_qtensor_to[xpu]
==================================================== 2 passed, 12 deselected in 2.13s ====================================================
```

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/optimum-quanto/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you run all tests locally and make sure they pass.
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by faaany** [comment]
@dacorvo I think the failed tests are not related to my PR.

**Comment by dacorvo** [comment]
@faaany thank you for your pull-request. You are correct: the tests are failing because the fix for #319 did not make it to pytorch 2.5.1. I just got the information that it will be fixed only in 2.6.0, so in order to have the tests pass, you need to modify the version check here to require `>= 2.6.0`:
https://github.com/huggingface/optimum-quanto/blob/7aaf99e5bcd58755ccbe590593201f2174d2a60a/optimum/quanto/library/qbytes_mm.py#L95

**Comment by faaany** [comment]
@dacorvo thanks for the hint! pytorch version updated!

**Comment by faaany** [comment]
@dacorvo thanks so much! updated.

**Review by dacorvo — APPROVED** [review]
There is still an issue with the second commit message. I am approving anyway but will merge the changes in #349 .

**Comment by faaany** [comment]
> There is still an issue with the second commit message. I am approving anyway but will merge the changes in #349 .

thanks for the rebase and merge! Will pay attention to the commit message next time.

**Pull request closed without merging**
